apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetryreader
  labels:
    app: telemetryreader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetryreader
  template:
    metadata:
      labels:
        app: telemetryreader
    spec:
      containers:
      - name: telemetryreader
        image: aksiot.azurecr.io/telemetryreader:latest
        stdin: true
        ports:
        - containerPort: 443
        - containerPort: 5671
        - containerPort: 8883