apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetryreader
  labels:
    app: telemetryreader
spec:
  replicas: 0
  selector:
    matchLabels:
      app: telemetryreader
  template:
    metadata:
      labels:
        app: telemetryreader
    spec:
      containers:
      - name: telemetryreader
        image: aksiottest.azurecr.io/telemetryreader:1.0.5
        stdin: true
        ports:
        - containerPort: 443
        - containerPort: 5671
        - containerPort: 8883
      imagePullSecrets:
        - name: acrcreds
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule